/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-07-07 00:28:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webTest.fileUpLoad;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.sound.sampled.AudioFormat.Encoding;
import java.net.URLEncoder;
import java.io.File;

public final class fileList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("javax.sound.sampled.AudioFormat.Encoding");
    _jspx_imports_classes.add("java.io.File");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../../Model/mainForm/mainForm.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../Model/mainForm/mainForm.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원제 게시판 예시</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"mainForm.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<!-- 헤더 -->\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<a href=\"index.jsp\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"../../img/logo.png\"\r\n");
      out.write("\t\t\t\t\tstyle=\"position: relative; top: 20px; left: 10px\">\r\n");
      out.write("\t\t\t\t</a> <input type=\"text\" onclick=\"\"\r\n");
      out.write("\t\t\t\t\tstyle=\"position: relative; left: 20px;\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br> <a href=\"\" onmouseover=\"TextMover()\"\r\n");
      out.write("\t\t\t\t\tonmouseout=\"TextMount()\" id=\"nav\" style=\"color: black;\">차트</a>\r\n");
      out.write("\t\t\t\t&nbsp; <a href=\"../chart/recentMusic.jsp\" onmouseover=\"TextMover2()\"\r\n");
      out.write("\t\t\t\t\tonmouseout=\"TextMount2()\" id=\"nav2\" style=\"color: black;\">최신음악</a>\r\n");
      out.write("\t\t\t\t&nbsp; <a href=\"\" onmouseover=\"TextMover3()\"\r\n");
      out.write("\t\t\t\t\tonmouseout=\"TextMount3()\" id=\"nav3\" style=\"color: black;\">장르음악</a>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t<hr id=\"hr\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 콘텐츠 -->\r\n");
      out.write("\t<div id=\"content\" align=\"center\" style=\"background-color: #ffffff;\">\r\n");
      out.write("\t\t<section id=\"main_section\">\r\n");
      out.write("\t\t\t<article class=\"main_article\"></article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!-- 메인 섹션 건들지 말것. -->\r\n");
      out.write("\r\n");
      out.write("\t\t<aside id=\"main_aside\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty authUser }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\"></a>ㅇㅇㅇㅇㅇㅇ <a href=\"../login/signUp.jsp\">회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"image\" src=\"../../img/login/login.png\" \r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"height: 42px; width: 244px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</c:if> <c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty authUser}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authUser.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님, 안녕하세요.<br />\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/WebTest/LogoutHandler\">[로그아웃하기]</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"changePwdForm.jsp\">[암호변경하기]</a>\r\n");
      out.write("\t\t\t\t\t\t</c:if></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"downLoad.jsp\">Window다운로드</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("<aside id=\"main_bside\">\r\n");
      out.write("\r\n");
      out.write("\r\n");

String saveFolder="/upload";

ServletContext context = getServletContext();
//String savedir = context.getRealPath(saveFolder);

String savedir= "C:\\Users\\EaBEll\\Desktop\\java\\WebTest\\WebContent\\webTest\\upload";
String savedir3 = "C:\\Users\\EaBEll\\Desktop\\java\\.metadata\\.plugins\\org.eclipse.wst.server.core\\tmp0\\wtpwebapps\\WebTest\\webTest\\upload";


//String savedir2="C:\\Program Files (x86)\\Apache Software Foundation\\Tomcat 9.0\\webapps\\ROOT\\upload";

    
File dirFile= new File(savedir3);

File []fileList=dirFile.listFiles();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tr> \r\n");
      out.write("\t<td>파일명</td><td>다운로드</td>\r\n");

for(File tempFile : fileList) {
  if(tempFile.isFile()) {
	  String tempPath=tempFile.getParent();
    String tempFileName=tempFile.getName();   
    
    
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("   <td> ");
      out.print(tempFileName.toString() );
      out.write("</td>\t\r\n");
      out.write("\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"../upload/");
      out.print(tempFileName.toString() );
      out.write("\" download=\"");
      out.print(tempFileName.toString() );
      out.write("\"><button>파일 다운로드</button></a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t");
      out.print(request.getRealPath("/upload") );
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
 
    System.out.println("Path="+tempPath);
    System.out.println("FileName="+tempFileName);
    System.out.println(request.getServletPath());
  }
}

      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 바텀 -->\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
