/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-09-16 12:51:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webTest.View.fileUpLoad;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fileUpLoadForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset= UTF-8\" >\r\n");
      out.write("\r\n");
      out.write("<title>파일업로드</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/webTest/Model/login/info.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"/webTest/Model/mainForm/mainForm.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/webTest/Model/mainForm/mainForm.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/webTest/Model/login/info.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t<form action=\"mainForm.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<!-- 헤더 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"/index\" style=\"background: white;\"> \r\n");
      out.write("\t\t\t\t\t <img src=\"/webTest/img/logo.png\"\r\n");
      out.write("\t\t\t\t\t style=\"position: relative; top: 15px; left: 0px; width: 140px; width:140px\"></a>\r\n");
      out.write("\t\t\t\t\t  <input type=\"text\" onclick=\"\"\r\n");
      out.write("\t\t\t\t\tstyle=\"position: relative; left: 20px;\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<hr id=\"head_line\" size=\"10px\" color=\"#ECB237\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br> <a href=\"\" onmouseover=\"TextMover()\"\r\n");
      out.write("\t\t\t\t\tonmouseout=\"TextMount()\" id=\"nav\" style=\"color: black;\">차트</a>\r\n");
      out.write("\t\t\t\t&nbsp; <a href=\"/webTest/View/fileUpLoad/fileList.jsp\" onmouseover=\"TextMover2()\"\r\n");
      out.write("\t\t\t\t\tonmouseout=\"TextMount2()\" id=\"nav2\" style=\"color: black;\">최신음악</a>\r\n");
      out.write("\t\t\t\t&nbsp; <a href=\"\" onmouseover=\"TextMover3()\"\r\n");
      out.write("\t\t\t\t\tonmouseout=\"TextMount3()\" id=\"nav3\" style=\"color: black;\">장르음악</a>\r\n");
      out.write("\t\t\t\t\t\t&nbsp; <a href=\"/webTest/article/list.jsp\"  id=\"nav3\" style=\"color: black;\">게시판</a>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("\t\t<hr id=\"head_line\" size=\"10px\" color=\"#ECB237\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t<!-- 사이드 컨텐츠 -->\r\n");
      out.write("\t<div style=\"padding:10px; width: 30%; float: right;\">\r\n");
      out.write("\t\t<aside id=\"main_aside\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty authUser }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<div align=\"center\"><a href=\"\"></a> <a href=\"/webTest/login/signUp.jsp\">회원가입</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/webTest/login/login.jsp\" ><img alt=\"\" src=\"/webTest/img/login/login.png\" style=\"height: 42px; width: 244px;\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</c:if> <c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty authUser}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authUser.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님, 안녕하세요.<br />\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/LogoutHandler\">[로그아웃하기]</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"changePwdForm.jsp\">[암호변경하기]</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/webTest/list/newMusicForm.jsp\">[마이페이지]</a>\r\n");
      out.write("\t\t\t\t\t\t</c:if></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<a href=\"/webTest/나는가수다.msi\" download=>Window다운로드</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"content\"  style=\" padding:10px; width: 65%;  float: left;\" >\r\n");
      out.write("\r\n");
      out.write("<!-- 메인 컨텐츠 -->\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action =\"01_FileUpload.jsp\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t<table border = \"1\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t <tr>\r\n");
      out.write("\t  <td colspan=\"2\" align=\"center\"><h3>파일업로드 폼</h3></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>올린 사람</td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>제목</td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"subject\"></td>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>파일명1:</td>\r\n");
      out.write("\t\t<td><input type=\"file\" name = \"fileName1\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>파일명2: </td>\r\n");
      out.write("\t\t<td><input type=\"file\" name=\"fileName2\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" align=\"center\"><input type=\"submit\" value=\"전송\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- 바텀 -->\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
