/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-08-30 11:16:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webTest.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 회원가입테스트중_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style_mj.css\">\r\n");
      out.write(" </head>\r\n");
      out.write(" <body>\r\n");
      out.write(" <basefont size=6>\r\n");
      out.write(" <table width=\"940\">\r\n");
      out.write(" <form name=\"write_form_member\" method=\"post\">\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td><img src=\"../images/member/join1_top.gif\"></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr height=\"327px\">\r\n");
      out.write("     <td colspan=\"2\" align=\"left\" valign=\"top\" style=\"20px 0px 0px 0px;\">\r\n");
      out.write("     <!---------------------내용시작------------------>\r\n");
      out.write("   <table width=\"780\">\r\n");
      out.write("     <tr>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td>\r\n");
      out.write(" \r\n");
      out.write("         <!--테이블 시작 -->\r\n");
      out.write("         <table width=\"940\" style=\"padding:5px 0 5px 0;\">\r\n");
      out.write("         <tr>\r\n");
      out.write("           <th>이름</th>\r\n");
      out.write("          <td><input type=\"text\" name=\"mbname\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write(" \r\n");
      out.write("        <tr>\r\n");
      out.write("         <th>주민등록번호</th>\r\n");
      out.write("         <td><input type=\"text\" name=\"jumin_1\"> -\r\n");
      out.write("         <input type=\"password\" name=\"jumin_2\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write(" \r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>아이디</th>\r\n");
      out.write("         <td> <input type=\"text\" name=\"mbid\"><a href='#' style='cursor:pointer'></a> (영문/숫자 10~12자) </td>\r\n");
      out.write("      </tr>\r\n");
      out.write(" \r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>비밀번호</th>\r\n");
      out.write("         <td><input type=\"password\" name=\"mbpw\"> 영문/숫자포함 6자 이상</td>\r\n");
      out.write("      </tr>\r\n");
      out.write(" \r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>비밀번호 확인</th>\r\n");
      out.write("         <td><input type=\"password\" name=\"mbpw_re\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write(" \r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>비밀번호 힌트 답변</th>\r\n");
      out.write("         <td><select name='pwhint' size='1' class='select'>\r\n");
      out.write("         <option value=''>선택하세요 </option>\r\n");
      out.write("         <option value='30'>졸업한 초등학교 이름은?</option>\r\n");
      out.write("         <option value='31'>제일 친한 친구의 핸드폰 번호는? </option>\r\n");
      out.write("         <option value='32'>아버지 성함은?</option>\r\n");
      out.write("         <option value='33'>어머니 성함은?</option>\r\n");
      out.write("         <option value='34'>어릴 적 내 별명은?</option>\r\n");
      out.write("         <option value='35'>가장 아끼는 물건은?</option>\r\n");
      out.write("         <option value='36'>좋아하는 동물은?</option>\r\n");
      out.write("         <option value='37'>좋아하는 색깔은?</option>\r\n");
      out.write("         <option value='38'>좋아하는 음식은?</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      </tr>\r\n");
      out.write(" \r\n");
      out.write("      <tr>\r\n");
      out.write("      </td>\r\n");
      out.write("         <th>답변</th>\r\n");
      out.write("         <td><input type='text' name=\"pwhintans\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write(" \r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>이메일</th>\r\n");
      out.write("         <td>\r\n");
      out.write("            <input type=\"text\" name=\"email\"> @\r\n");
      out.write("            <input type=\"text\" name=\"email_dns\">\r\n");
      out.write("               <select name=\"emailaddr\">\r\n");
      out.write("                  <option value=\"\">직접입력</option>\r\n");
      out.write("                  <option value=\"daum.net\">daum.net</option>\r\n");
      out.write("                  <option value=\"empal.com\">empal.com</option>\r\n");
      out.write("                  <option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("                  <option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("                  <option value=\"msn.com\">msn.com</option>\r\n");
      out.write("                  <option value=\"naver.com\">naver.com</option>\r\n");
      out.write("                  <option value=\"nate.com\">nate.com</option>\r\n");
      out.write("               </select>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write(" \r\n");
      out.write("         <tr>\r\n");
      out.write("            <th>주소</th>\r\n");
      out.write("            <td>\r\n");
      out.write("               <input type=\"text\" name=\"zip_h_1\"> - \r\n");
      out.write("               <input type=\"text\" name=\"zip_h_2\">\r\n");
      out.write("               <a href='#' style='cursor:hand;'>\r\n");
      out.write("               <img src=\"../images/member/btn_zipcode.gif\" style=\"cursor:pointer\"></a><br>\r\n");
      out.write("               <input type=\"text\" name=\"addr_h1\"><br>\r\n");
      out.write("               <input type=\"text\" name=\"addr_h1\">\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write(" \r\n");
      out.write("         <tr>\r\n");
      out.write("         <th>전화번호</th>\r\n");
      out.write("         <td><input type=\"text\" name=\"cel1\"> - \r\n");
      out.write("            <input type=\"text\" name=\"cel2_1\" title=\"전화번호\"> -\r\n");
      out.write("            <input type=\"text\" name=\"cel2_2\">\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write(" \r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>핸드폰 번호</th>\r\n");
      out.write("         <td><input type=\"text\" name=\"tel_h1\"> - \r\n");
      out.write("            <input type=\"text\" name=\"tel_h2_1\"> -\r\n");
      out.write("            <input type=\"text\" name=\"tel_h2_2\">\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   <!--테이블 끝-->\r\n");
      out.write("   </td>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <!-- 회원가입 완료와 취소 -->\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td colspan=\"2\" align=\"center\">\r\n");
      out.write("         <div id=\"member_button\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("         <img src=\"../images/member/s01_sub_bt_save.gif\" width=\"104\" height=\"34\" border=\"0\"></a>\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("         <img src=\"../images/member/s01_sub_bt_cancel.gif\" width=\"104\" height=\"34\" border=\"0\"></a>\r\n");
      out.write("         <div>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("  </td>\r\n");
      out.write(" </tr>\r\n");
      out.write("</form>\r\n");
      out.write("</table>        \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write(" \r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
